# -*- coding: utf-8 -*-
"""Regresion Polinomial Modificada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JfnuI2UncRG70ybAaD93Oes3JtKDUHun
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

datos_x = np.array([108, 115, 106, 97, 95, 91, 97, 83, 83, 78, 54, 67, 56, 53, 61, 115, 81, 78, 30, 45, 99, 32, 25, 28, 90, 89])
datos_y = np.array([95, 96, 95, 97, 93, 94, 95, 93, 92, 86, 73, 80, 65, 69, 77, 96, 87, 89, 60, 63, 95, 61, 55, 56, 94, 93])

transformador = PolynomialFeatures(degree=3, include_bias=False)
datos_x_poly = transformador.fit_transform(datos_x.reshape(-1, 1))

regresion_modelo = LinearRegression()
regresion_modelo.fit(datos_x_poly, datos_y)

nuevos_x = np.array([120, 135])

nuevos_x_poly = transformador.transform(nuevos_x.reshape(-1, 1))
predicciones_y = regresion_modelo.predict(nuevos_x_poly)

ajuste_x = np.linspace(1, 115, 100)
ajuste_x_poly = transformador.transform(ajuste_x.reshape(-1, 1))
ajuste_y = regresion_modelo.predict(ajuste_x_poly)

plt.scatter(datos_x, datos_y)
plt.plot(ajuste_x, ajuste_y, color='red')
plt.show()
